#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh

for folder in $(echo "git,nvim,tmux,zsh" | sed "s/,/ /g")
do
    echo "Removing $folder"
    stow -D $folder
done
popd
